version: '3'

services:
  web:
    container_name: pictomaker-lite-api
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app:app
      --host 0.0.0.0 --port 5055
      --reload"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5055:5055"
